// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SalesHub.Infrastructure.Persistence;

#nullable disable

namespace SalesHub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SalesHubDbContext))]
    [Migration("20260811004758_WaveThreeFormsResources")]
    partial class WaveThreeFormsResources
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_claims_role_id");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("SalesHub.Domain.Entities.Announcement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcknowledgeByUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledge_by_utc");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at_utc");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<DateTimeOffset?>("AutoUnpinAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("auto_unpin_at_utc");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("character varying(16000)")
                        .HasColumnName("body");

                    b.Property<bool>("CompletionNotified")
                        .HasColumnType("boolean")
                        .HasColumnName("completion_notified");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("LastReminderAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_reminder_at_utc");

                    b.Property<int?>("PinRank")
                        .HasColumnType("integer")
                        .HasColumnName("pin_rank");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("priority");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<int?>("ReminderEveryHours")
                        .HasColumnType("integer")
                        .HasColumnName("reminder_every_hours");

                    b.Property<bool>("RequireAcknowledgment")
                        .HasColumnType("boolean")
                        .HasColumnName("require_acknowledgment");

                    b.Property<DateTimeOffset?>("ScheduledPublishAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_publish_at_utc");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("ViewByUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("view_by_utc");

                    b.HasKey("Id")
                        .HasName("pk_announcements");

                    b.HasIndex("PinRank")
                        .HasDatabaseName("ix_announcements_pin_rank");

                    b.HasIndex("PublishedAtUtc")
                        .HasDatabaseName("ix_announcements_published_at_utc");

                    b.HasIndex("ScheduledPublishAtUtc")
                        .HasDatabaseName("ix_announcements_scheduled_publish_at_utc")
                        .HasFilter("published_at_utc IS NULL AND archived_at_utc IS NULL");

                    b.ToTable("announcements", (string)null);
                });

            modelBuilder.Entity("SalesHub.Domain.Entities.AnnouncementTarget", b =>
                {
                    b.Property<Guid>("AnnouncementId")
                        .HasColumnType("uuid")
                        .HasColumnName("announcement_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset?>("AcknowledgedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at_utc");

                    b.Property<bool>("CountsTowardCompletion")
                        .HasColumnType("boolean")
                        .HasColumnName("counts_toward_completion");

                    b.Property<DateTimeOffset?>("SeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("seen_at_utc");

                    b.HasKey("AnnouncementId", "UserId")
                        .HasName("pk_announcement_targets");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_announcement_targets_user_id");

                    b.ToTable("announcement_targets", (string)null);
                });

            modelBuilder.Entity("SalesHub.Domain.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("AfterJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_json");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_json");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("PublicRecordId")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("public_record_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("RetentionClass")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("retention_class");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("target_type");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("ix_audit_events_occurred_at_utc");

                    b.HasIndex("ActorUserId", "OccurredAtUtc")
                        .HasDatabaseName("ix_audit_events_actor_user_id_occurred_at_utc");

                    b.HasIndex("Category", "OccurredAtUtc")
                        .HasDatabaseName("ix_audit_events_category_occurred_at_utc");

                    b.HasIndex("TargetType", "TargetId")
                        .HasDatabaseName("ix_audit_events_target_type_target_id");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("SalesHub.Domain.Entities.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone_id");

                    b.HasKey("Id")
                        .HasName("pk_branches");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_branches_name");

                    b.ToTable("branches", (string)null);
                });

            modelBuilder.Entity("SalesHub.Domain.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("DirectKey")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("direct_key");

                    b.Property<bool>("Mandatory")
                        .HasColumnType("boolean")
                        .HasColumnName("mandatory");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_conversations");

                    b.HasIndex("DirectKey")
                        .IsUnique()
                        .HasDatabaseName("ix_conversations_direct_key");

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("SalesHub.Domain.Entities.ConversationMember", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at_utc");

                    b.Property<DateTimeOffset?>("LastReadAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_read_at_utc");

                    b.Property<Guid?>("LastReadMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_read_message_id");

                    b.Property<DateTimeOffset?>("MutedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("muted_at_utc");

                    b.HasKey("ConversationId", "UserId")
                        .HasName("pk_conversation_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_conversation_members_user_id");

                    b.ToTable("conversation_members", (string)null);
                });

            modelBuilder.Entity("SalesHub.Domain.Entities.EmailRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cid")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cid");

                    b.Property<string>("Coverage")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("coverage");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("customer_email");

                    b.Property<string>("LawnArea")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("lawn_area");

                    b.Property<string>("QuoteType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("quote_type");

                    b.Property<Guid>("SubmitterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("submitter_user_id");

                    b.HasKey("Id")
                        .HasName("pk_email_requests");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_email_requests_created_at_utc");

                    b.ToTable("email_requests", (string)null);
                });

            modelBuilder.Entity("SalesHub.Domain.Entities.FileBlob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ByteLength")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_length");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("original_name");

                    b.Property<DateTimeOffset?>("PurgeEligibleAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purge_eligible_at_utc");

                    b.Property<string>("ScanStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("scan_status");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("storage_key");

                    b.HasKey("Id")
                        .HasName("pk_file_blobs");

                    b.HasIndex("Sha256")
                        .HasDatabaseName("ix_file_blobs_sha256");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("ix_file_blobs_storage_key");

                    b.ToTable("file_blobs", (string)null);
                });

            modelBuilder.Entity("SalesHub.Domain.Entities.Form", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid?>("CurrentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_version_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("external_url");

                    b.Property<int?>("PinRank")
                        .HasColumnType("integer")
                        .HasColumnName("pin_rank");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<bool>("TracksCompletion")
                        .HasColumnType("boolean")
                        .HasColumnName("tracks_completion");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_forms");

                    b.ToTable("forms", (string)null);
                });

            modelBuilder.Entity("SalesHub.Domain.Entities.FormSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnswersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("answers_json");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<Guid?>("CompletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("completed_by_user_id");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uuid")
                        .HasColumnName("form_id");

                    b.Property<Guid>("FormVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("form_version_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_form_submissions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_form_submissions_user_id");

                    b.HasIndex("FormId", "SubmittedAtUtc")
                        .HasDatabaseName("ix_form_submissions_form_id_submitted_at_utc");

                    b.ToTable("form_submissions", (string)null);
                });

            modelBuilder.Entity("SalesHub.Domain.Entities.FormVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("definition_json");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uuid")
                        .HasColumnName("form_id");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_form_versions");

                    b.HasIndex("FormId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_form_versions_form_id_version_number");

                    b.ToTable("form_versions", (string)null);
                });

            modelBuilder.Entity("SalesHub.Domain.Entities.IdempotencyKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("operation");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_json");

                    b.Property<int>("ResponseStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("response_status_code");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_idempotency_keys");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_idempotency_keys_expires_at_utc");

                    b.HasIndex("UserId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_idempotency_keys_user_id_key");

                    b.ToTable("idempotency_keys", (string)null);
                });

            modelBuilder.Entity("SalesHub.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("body");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<DateTimeOffset?>("EditedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at_utc");

                    b.Property<Guid?>("ReplyToMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("reply_to_message_id");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_user_id");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("ConversationId", "Id")
                        .HasDatabaseName("ix_messages_conversation_id_id");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("SalesHub.Domain.Entities.MessageAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BlobId")
                        .HasColumnType("uuid")
                        .HasColumnName("blob_id");

                    b.Property<long>("ByteLength")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_length");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("content_type");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("original_name");

                    b.HasKey("Id")
                        .HasName("pk_message_attachments");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("ix_message_attachments_message_id");

                    b.ToTable("message_attachments", (string)null);
                });

            modelBuilder.Entity("SalesHub.Domain.Entities.MessageReaction", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Reaction")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("reaction");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.HasKey("MessageId", "UserId", "Reaction")
                        .HasName("pk_message_reactions");

                    b.ToTable("message_reactions", (string)null);
                });

            modelBuilder.Entity("SalesHub.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcknowledgedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at_utc");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<bool>("ProtectedFromClear")
                        .HasColumnType("boolean")
                        .HasColumnName("protected_from_clear");

                    b.Property<DateTimeOffset?>("ReadAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at_utc");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reference_type");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean")
                        .HasColumnName("required");

                    b.Property<string>("SafePreview")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("safe_preview");

                    b.Property<DateTimeOffset?>("SnoozedUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("snoozed_until_utc");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId", "CreatedAtUtc")
                        .HasDatabaseName("ix_notifications_user_id_created_at_utc");

                    b.HasIndex("UserId", "ReadAtUtc")
                        .HasDatabaseName("ix_notifications_user_id_read_at_utc");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("SalesHub.Domain.Entities.NotificationDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset?>("DeliveredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at_utc");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("notification_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_notification_deliveries");

                    b.HasIndex("NotificationId")
                        .HasDatabaseName("ix_notification_deliveries_notification_id");

                    b.ToTable("notification_deliveries", (string)null);
                });

            modelBuilder.Entity("SalesHub.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("AvailableAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at_utc");

                    b.Property<DateTimeOffset?>("ClaimedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at_utc");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("event_type");

                    b.Property<bool>("Failed")
                        .HasColumnType("boolean")
                        .HasColumnName("failed");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("AvailableAtUtc")
                        .HasDatabaseName("ix_outbox_pending")
                        .HasFilter("processed_at_utc IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("SalesHub.Domain.Entities.PasswordResetRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("HandledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("handled_at_utc");

                    b.Property<Guid?>("HandledByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("handled_by_user_id");

                    b.Property<Guid?>("MatchedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("matched_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("UsernameSubmitted")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("username_submitted");

                    b.HasKey("Id")
                        .HasName("pk_password_reset_requests");

                    b.HasIndex("Status", "CreatedAtUtc")
                        .HasDatabaseName("ix_password_reset_requests_status_created_at_utc");

                    b.ToTable("password_reset_requests", (string)null);
                });

            modelBuilder.Entity("SalesHub.Domain.Entities.PublicIdSequence", b =>
                {
                    b.Property<string>("Prefix")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("prefix");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.Property<int>("LastValue")
                        .HasColumnType("integer")
                        .HasColumnName("last_value");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Prefix", "Year")
                        .HasName("pk_public_id_sequences");

                    b.ToTable("public_id_sequences", (string)null);
                });

            modelBuilder.Entity("SalesHub.Domain.Entities.PushSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("auth");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DisabledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at_utc");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("endpoint");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("p256dh");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_push_subscriptions");

                    b.HasIndex("Endpoint")
                        .IsUnique()
                        .HasDatabaseName("ix_push_subscriptions_endpoint");

                    b.HasIndex("UserId", "Active")
                        .HasDatabaseName("ix_push_subscriptions_user_id_active");

                    b.ToTable("push_subscriptions", (string)null);
                });

            modelBuilder.Entity("SalesHub.Domain.Entities.Recognition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActiveUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("active_until_utc");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at_utc");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<Guid>("BadgeId")
                        .HasColumnType("uuid")
                        .HasColumnName("badge_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("message");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_user_id");

                    b.HasKey("Id")
                        .HasName("pk_recognitions");

                    b.HasIndex("ArchivedAtUtc")
                        .HasDatabaseName("ix_recognitions_archived_at_utc");

                    b.HasIndex("RecipientUserId")
                        .HasDatabaseName("ix_recognitions_recipient_user_id");

                    b.ToTable("recognitions", (string)null);
                });

            modelBuilder.Entity("SalesHub.Domain.Entities.RecognitionBadge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<bool>("BuiltIn")
                        .HasColumnType("boolean")
                        .HasColumnName("built_in");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("emoji");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_recognition_badges");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_recognition_badges_name");

                    b.ToTable("recognition_badges", (string)null);
                });

            modelBuilder.Entity("SalesHub.Domain.Entities.RecognitionComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("RecognitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("recognition_id");

                    b.HasKey("Id")
                        .HasName("pk_recognition_comments");

                    b.HasIndex("RecognitionId")
                        .HasDatabaseName("ix_recognition_comments_recognition_id");

                    b.ToTable("recognition_comments", (string)null);
                });

            modelBuilder.Entity("SalesHub.Domain.Entities.RecognitionReaction", b =>
                {
                    b.Property<Guid>("RecognitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("recognition_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Reaction")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("reaction");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.HasKey("RecognitionId", "UserId", "Reaction")
                        .HasName("pk_recognition_reactions");

                    b.ToTable("recognition_reactions", (string)null);
                });

            modelBuilder.Entity("SalesHub.Domain.Entities.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BlobId")
                        .HasColumnType("uuid")
                        .HasColumnName("blob_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("external_url");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("uuid")
                        .HasColumnName("folder_id");

                    b.Property<bool>("SensitiveStagingPlaceholder")
                        .HasColumnType("boolean")
                        .HasColumnName("sensitive_staging_placeholder");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_resources");

                    b.HasIndex("FolderId")
                        .HasDatabaseName("ix_resources_folder_id");

                    b.ToTable("resources", (string)null);
                });

            modelBuilder.Entity("SalesHub.Domain.Entities.ResourceDownloadAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceTitle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("resource_title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("Watermarked")
                        .HasColumnType("boolean")
                        .HasColumnName("watermarked");

                    b.HasKey("Id")
                        .HasName("pk_resource_download_audit");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("ix_resource_download_audit_occurred_at_utc");

                    b.ToTable("resource_download_audit", (string)null);
                });

            modelBuilder.Entity("SalesHub.Domain.Entities.ResourceFavorite", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.HasKey("UserId", "ResourceId")
                        .HasName("pk_resource_favorites");

                    b.ToTable("resource_favorites", (string)null);
                });

            modelBuilder.Entity("SalesHub.Domain.Entities.ResourceFolder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_resource_folders");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_resource_folders_parent_id");

                    b.ToTable("resource_folders", (string)null);
                });

            modelBuilder.Entity("SalesHub.Domain.Entities.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("date")
                        .HasColumnName("business_date");

                    b.Property<string>("Campaign")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("campaign");

                    b.Property<string>("Cid")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<string>("SaleType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("sale_type");

                    b.Property<Guid>("SellerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_user_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_sales");

                    b.HasIndex("BusinessDate")
                        .HasDatabaseName("ix_sales_business_date");

                    b.HasIndex("Cid", "BusinessDate")
                        .HasDatabaseName("ix_sales_cid_business_date");

                    b.HasIndex("SellerUserId", "BusinessDate")
                        .HasDatabaseName("ix_sales_seller_user_id_business_date");

                    b.ToTable("sales", (string)null);
                });

            modelBuilder.Entity("SalesHub.Domain.Entities.SaleCorrection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("AfterJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("after_json");

                    b.Property<string>("BeforeJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("before_json");

                    b.Property<string>("CorrectionType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("correction_type");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("reason");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("sale_id");

                    b.HasKey("Id")
                        .HasName("pk_sale_corrections");

                    b.HasIndex("SaleId")
                        .HasDatabaseName("ix_sale_corrections_sale_id");

                    b.ToTable("sale_corrections", (string)null);
                });

            modelBuilder.Entity("SalesHub.Domain.Entities.SaleDuplicateOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at_utc");

                    b.Property<Guid>("ConfirmedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_by_user_id");

                    b.Property<Guid>("PriorSaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("prior_sale_id");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("sale_id");

                    b.HasKey("Id")
                        .HasName("pk_sale_duplicate_overrides");

                    b.HasIndex("PriorSaleId")
                        .HasDatabaseName("ix_sale_duplicate_overrides_prior_sale_id");

                    b.HasIndex("SaleId")
                        .HasDatabaseName("ix_sale_duplicate_overrides_sale_id");

                    b.ToTable("sale_duplicate_overrides", (string)null);
                });

            modelBuilder.Entity("SalesHub.Domain.Entities.ScheduledJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("cron_expression");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("JobKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("job_key");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("job_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LastFailureAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_failure_at_utc");

                    b.Property<DateTimeOffset?>("LastSuccessAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_success_at_utc");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at_utc");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("lease_owner");

                    b.Property<DateTimeOffset?>("NextRunAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_run_at_utc");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone_id");

                    b.HasKey("Id")
                        .HasName("pk_scheduled_jobs");

                    b.HasIndex("JobKey")
                        .IsUnique()
                        .HasDatabaseName("ix_scheduled_jobs_job_key");

                    b.HasIndex("NextRunAtUtc")
                        .HasDatabaseName("ix_scheduled_jobs_next_run_at_utc")
                        .HasFilter("enabled");

                    b.ToTable("scheduled_jobs", (string)null);
                });

            modelBuilder.Entity("SalesHub.Domain.Entities.ScheduledJobRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("ErrorClass")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("error_class");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<DateTimeOffset>("ScheduledForUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for_utc");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("boolean")
                        .HasColumnName("succeeded");

                    b.HasKey("Id")
                        .HasName("pk_scheduled_job_runs");

                    b.HasIndex("JobId", "StartedAtUtc")
                        .HasDatabaseName("ix_scheduled_job_runs_job_id_started_at_utc");

                    b.ToTable("scheduled_job_runs", (string)null);
                });

            modelBuilder.Entity("SalesHub.Domain.Entities.TaskAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BlobId")
                        .HasColumnType("uuid")
                        .HasColumnName("blob_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("content_type");

                    b.Property<Guid>("DefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("definition_id");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("original_name");

                    b.HasKey("Id")
                        .HasName("pk_task_attachments");

                    b.HasIndex("DefinitionId")
                        .HasDatabaseName("ix_task_attachments_definition_id");

                    b.ToTable("task_attachments", (string)null);
                });

            modelBuilder.Entity("SalesHub.Domain.Entities.TaskComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.HasKey("Id")
                        .HasName("pk_task_comments");

                    b.HasIndex("InstanceId")
                        .HasDatabaseName("ix_task_comments_instance_id");

                    b.ToTable("task_comments", (string)null);
                });

            modelBuilder.Entity("SalesHub.Domain.Entities.TaskDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("DueAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at_utc");

                    b.Property<bool>("OverdueReminders")
                        .HasColumnType("boolean")
                        .HasColumnName("overdue_reminders");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("priority");

                    b.Property<string>("Recurrence")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("recurrence");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_task_definitions");

                    b.ToTable("task_definitions", (string)null);
                });

            modelBuilder.Entity("SalesHub.Domain.Entities.TaskInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssigneeUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_user_id");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("definition_id");

                    b.Property<DateTimeOffset?>("DueAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at_utc");

                    b.Property<DateTimeOffset?>("LastOverdueReminderAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_overdue_reminder_at_utc");

                    b.Property<string>("PeriodKey")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("period_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_task_instances");

                    b.HasIndex("AssigneeUserId", "Status")
                        .HasDatabaseName("ix_task_instances_assignee_user_id_status");

                    b.HasIndex("DefinitionId", "AssigneeUserId", "PeriodKey")
                        .IsUnique()
                        .HasDatabaseName("ix_task_instances_definition_id_assignee_user_id_period_key");

                    b.ToTable("task_instances", (string)null);
                });

            modelBuilder.Entity("SalesHub.Domain.Entities.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("app_version");

                    b.Property<string>("BrowserFamily")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("browser_family");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset?>("FreshAuthUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fresh_auth_until_utc");

                    b.Property<DateTimeOffset?>("IdleCapabilityLeaseUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("idle_capability_lease_until_utc");

                    b.Property<string>("IdleCapabilityState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("idle_capability_state");

                    b.Property<DateTimeOffset?>("IdleDetectorStartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("idle_detector_started_at_utc");

                    b.Property<DateTimeOffset?>("IdlePermissionVerifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("idle_permission_verified_at_utc");

                    b.Property<string>("IpHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_hash");

                    b.Property<DateTimeOffset?>("LastIdleHeartbeatAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_idle_heartbeat_at_utc");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<string>("OsFamily")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("os_family");

                    b.Property<bool>("PwaInstalled")
                        .HasColumnType("boolean")
                        .HasColumnName("pwa_installed");

                    b.Property<string>("RevokeReason")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("revoke_reason");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<Guid?>("RevokedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by_user_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_sessions");

                    b.HasIndex("IdleCapabilityLeaseUntilUtc")
                        .HasDatabaseName("ix_user_sessions_idle_capability_lease_until_utc")
                        .HasFilter("revoked_at_utc IS NULL");

                    b.HasIndex("LastSeenAtUtc")
                        .HasDatabaseName("ix_user_sessions_last_seen_at_utc");

                    b.HasIndex("UserId", "RevokedAtUtc")
                        .HasDatabaseName("ix_user_sessions_user_id_revoked_at_utc");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("SalesHub.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("SalesHub.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("date")
                        .HasColumnName("birthday");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DeactivatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at_utc");

                    b.Property<Guid?>("DeactivatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deactivated_by_user_id");

                    b.Property<string>("DeactivationReason")
                        .HasColumnType("text")
                        .HasColumnName("deactivation_reason");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<DateOnly?>("HireDate")
                        .HasColumnType("date")
                        .HasColumnName("hire_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<Guid?>("ProfilePhotoBlobId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_photo_blob_id");

                    b.Property<DateTimeOffset?>("ReactivationNoticeSentAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reactivation_notice_sent_at_utc");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset?>("ScheduledReactivationAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_reactivation_at_utc");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("SalesHub.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_claims_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("SalesHub.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("SalesHub.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("SalesHub.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("SalesHub.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("SalesHub.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
